INSERT INTO team (name, acronym, budget) VALUES ('Olympique Gymnaste Club de Nice', 'NCE', 100000000);
INSERT INTO player (name, position, team_id) VALUES ('Badredine Bouanani', 'F', 1);
INSERT INTO player (name, position, team_id) VALUES ('Gaëtan Laborde', 'F', 1);
INSERT INTO player (name, position, team_id) VALUES ('Billal Brahimi', 'F', 1);
INSERT INTO player (name, position, team_id) VALUES ('Sofiane Diop', 'F', 1);
INSERT INTO player (name, position, team_id) VALUES ('Terem Moffi', 'F', 1);
INSERT INTO player (name, position, team_id) VALUES ('Alexis Claude-Maurice', 'F', 1);
INSERT INTO player (name, position, team_id) VALUES ('Kasper Dolberg', 'F', 1);
INSERT INTO player (name, position, team_id) VALUES ('Evann Guessand', 'F', 1);
INSERT INTO player (name, position, team_id) VALUES ('Calvin Stengs', 'F', 1);
INSERT INTO player (name, position, team_id) VALUES ('Hichem Boudaoui', 'M', 1);
INSERT INTO player (name, position, team_id) VALUES ('Alexis Beka Beka', 'M', 1);
INSERT INTO player (name, position, team_id) VALUES ('Khéphren Thuram', 'M', 1);
INSERT INTO player (name, position, team_id) VALUES ('Aaron Ramsey', 'M', 1);
INSERT INTO player (name, position, team_id) VALUES ('Pablo Rosario', 'M', 1);
INSERT INTO player (name, position, team_id) VALUES ('Jean N''Guessan', 'M', 1);
INSERT INTO player (name, position, team_id) VALUES ('Youssouf Ndayishimiye', 'D', 1);
INSERT INTO player (name, position, team_id) VALUES ('Mattia Viti', 'D', 1);
INSERT INTO player (name, position, team_id) VALUES ('Melvin Bard', 'D', 1);
INSERT INTO player (name, position, team_id) VALUES ('Jean-Clair Todibo', 'D', 1);
INSERT INTO player (name, position, team_id) VALUES ('Jordan Lotomba', 'D', 1);
INSERT INTO player (name, position, team_id) VALUES ('Youcef Atal', 'D', 1);
INSERT INTO player (name, position, team_id) VALUES ('Dante', 'D', 1);
INSERT INTO player (name, position, team_id) VALUES ('Marcin Bułka', 'G', 1);
INSERT INTO player (name, position, team_id) VALUES ('Teddy Boulhendi', 'G', 1);
INSERT INTO player (name, position, team_id) VALUES ('Kasper Schmeichel', 'G', 1);

INSERT INTO team (name, acronym, budget) VALUES ('Paris Saint-Germain Football Club', 'PSG', 700000000);
INSERT INTO player (name, position, team_id) VALUES ('Kylian Mbappé', 'F', 2);
INSERT INTO player (name, position, team_id) VALUES ('Neymar Jr', 'F', 2);
INSERT INTO player (name, position, team_id) VALUES ('Lionel Messi', 'F', 2);
INSERT INTO player (name, position, team_id) VALUES ('Hugo Ekitike', 'F', 2);
INSERT INTO player (name, position, team_id) VALUES ('Marco Verratti', 'M', 2);
INSERT INTO player (name, position, team_id) VALUES ('Fabián Ruiz', 'M', 2);
INSERT INTO player (name, position, team_id) VALUES ('Danilo Pereira', 'M', 2);
INSERT INTO player (name, position, team_id) VALUES ('Vitinha', 'M', 2);
INSERT INTO player (name, position, team_id) VALUES ('Renato Sanches', 'M', 2);
INSERT INTO player (name, position, team_id) VALUES ('Carlos Soler', 'M', 2);
INSERT INTO player (name, position, team_id) VALUES ('Achraf Hakimi', 'D', 2);
INSERT INTO player (name, position, team_id) VALUES ('Presnel Kimpembe', 'D', 2);
INSERT INTO player (name, position, team_id) VALUES ('Sergio Ramos', 'D', 2);
INSERT INTO player (name, position, team_id) VALUES ('Marquinhos', 'D', 2);
INSERT INTO player (name, position, team_id) VALUES ('Juan Bernat', 'D', 2);
INSERT INTO player (name, position, team_id) VALUES ('Nuno Mendes', 'D', 2);
INSERT INTO player (name, position, team_id) VALUES ('Nordi Mukiele', 'D', 2);
INSERT INTO player (name, position, team_id) VALUES ('Timothée Pembélé', 'D', 2);
INSERT INTO player (name, position, team_id) VALUES ('Sergio Rico', 'G', 2);
INSERT INTO player (name, position, team_id) VALUES ('Alexandre Letellier', 'G', 2);
INSERT INTO player (name, position, team_id) VALUES ('Gianluigi Donnarumma', 'G', 2);

INSERT INTO team (name, acronym, budget) VALUES ('Olympique Lyonnais', 'LYO', 250000000);
INSERT INTO player (name, position, team_id) VALUES ('Anthony Lopes', 'G', 3);
INSERT INTO player (name, position, team_id) VALUES ('Rémy Riou', 'G', 3);
INSERT INTO player (name, position, team_id) VALUES ('Kayne Bonnevie', 'G', 3);
INSERT INTO player (name, position, team_id) VALUES ('Sinaly Diomandé', 'D', 3);
INSERT INTO player (name, position, team_id) VALUES ('Nicolás Tagliafico', 'D', 3);
INSERT INTO player (name, position, team_id) VALUES ('Castello Jr.', 'D', 3);
INSERT INTO player (name, position, team_id) VALUES ('Dejan Lovren', 'D', 3);
INSERT INTO player (name, position, team_id) VALUES ('Henrique', 'D', 3);
INSERT INTO player (name, position, team_id) VALUES ('Saël Kumbedi', 'D', 3);
INSERT INTO player (name, position, team_id) VALUES ('Youssouf Koné', 'D', 3);
INSERT INTO player (name, position, team_id) VALUES ('Irvyn Lomami', 'D', 3);
INSERT INTO player (name, position, team_id) VALUES ('Maxence Caqueret', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Romain Faivre', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Habib Keïta', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Jeff Reine-Adélaïde', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Thiago Mendes', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Johann Lepenant', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Mohamed El Arouch', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Corentin Tolisso', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Florent da Silva', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Camilo', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Mahamadou Diawara', 'M', 3);
INSERT INTO player (name, position, team_id) VALUES ('Amin Sarr', 'F', 3);
INSERT INTO player (name, position, team_id) VALUES ('Alexandre Lacazette', 'F', 3);
INSERT INTO player (name, position, team_id) VALUES ('Tino Kadewere', 'F', 3);
INSERT INTO player (name, position, team_id) VALUES ('Rayan Cherki', 'F', 3);
INSERT INTO player (name, position, team_id) VALUES ('Bradley Barcola', 'F', 3);
INSERT INTO player (name, position, team_id) VALUES ('Jeffinho', 'F', 3);
INSERT INTO player (name, position, team_id) VALUES ('Karl Toko-Ekambi', 'F', 3);
